'\" te
.\" Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
.TH nis 5 "9 Dec 2009" "SunOS 5.11" "Standards, Environments, and Macros"
.SH NAME
nis, NIS, NIS+ \- network information name service
.SH DESCRIPTION
.sp
.LP
NIS, formerly known as the Yellow Pages or YP, is the name of the network information name service in common use in networks on which Sun and other vendors' network nodes reside. The most recent version of NIS is version 2.
.sp
.LP
All commands and functions that use \fBNIS\fR version 2 are prefixed by the letters \fByp\fR as in \fBypmatch\fR(1), \fBypcat\fR(1), \fByp_match\fR(3NSL), and \fByp_first\fR(3NSL).
.sp
.LP
The NIS+ name service is no longer shipped with the Solaris operating system. Tools to aid the migration from NIS+ to LDAP are available in the current Solaris release.
