'\" te
.\"  Copyright 1989 AT&T  Copyright (c) 2003, Sun Microsystems, Inc.  All Rights Reserved.
.TH Intro 4 "16 Apr 2003" "SunOS 5.11" "File Formats"
.SH NAME
Intro, intro \- introduction to file formats
.SH DESCRIPTION
.sp
.LP
This section outlines the formats of various files. The C structure declarations for the file formats are given where applicable. Usually, the headers containing these structure declarations can be found in the directories \fB/usr/include\fR or \fB/usr/include/sys\fR. For inclusion in C language programs, however, the syntax \fB#include\fR <\fIfilename.h\fR> or \fB#include\fR <\fBsys/\fR\fIfilename.h\fR> should be used.
